# Generated by Django 5.2.6 on 2026-05-04 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50)),
                ('catego', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Turista', 'Turista'), ('Premium', 'Premium')], max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=7)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.hotel')),
            ],
        ),
    ]
